### ISSUE TITLE
How does this work as a static site without using TokamakStaticHTML?

### ISSUE THREAD

**Issue by revolter** [TokamakUI/tokamak-todo-example#3]
If I'm not mistaken, a static website means a website that can run without a server, right? Also, GitHub Pages only support static websites. So, knowing that this is published using GitHub Pages (https://tokamakui.github.io/tokamak-todo-example/), how come it works even though it's using

https://github.com/TokamakUI/tokamak-todo-example/blob/c5e5b230369ae8e3c68600bee84ebca69317bf61/Sources/tokamak-todo-example/main.swift#L1

instead of `TokamakStaticHTML`?

As I understood, `TokamakDOM` already exports `TokamakStaticHTML`, but `Button` doesn't come from the latter module. Doesn't this mean that it should not work in a static website?

**Comment by MaxDesiatov** [comment]
To be pedantic, there are actually three or four options here, depending on how you look at it:

1. A plain HTML website with all content pre-rendered. This is a base level that probably all websites should provide, plain HTML pages can be indexed by search engines and are also accessible by users who may have JavaScript turned off or use older browsers that don't support WebAssembly. The downside is that not all interactivity features can be supported with plain HTML.
2. A website that loads a WebAssembly app built with Tokamak. This is what `carton bundle` produces right now, the HTML page though has only a single element that's a placeholder into which an app is rendered dynamically when the WebAssembly module is fully loaded. Such WebAssembly modules are executed fully in the browser and don't need an interactive server component to work. The downside is that binaries produced by SwiftWasm are pretty big right now, these pages probably can't be easily indexed by search engines, and older browsers can't access them.
3. Non-static websites that require some server components to fully work.

We could separate a fourth option here with pure JavaScript apps that don't use WebAssembly, but those aren't relevant in our case since Swift does require WebAssembly to be executed in the browser.

Here points 1 and 2 represent static websites, and Tokamak Todo Example is deployed to GitHub Pages through the 2nd path. It's built with `carton bundle` with the empty HTML page and the WebAssemlby app committed to the repository and served through GitHub Pages CDN.

In the future we'd like `carton bundle` or some other tool support a mix of points 1 and 2. It would produce a pre-rendered HTML website, which could be indexed and accessible with any old browser, but would also load a WebAssembly module where available for interactivity.

Apps from the 3rd point with interactive server components are possible today too. The easy way to think about it: everything that's possible with JavaScript is also possible with SwiftWasm, because you can bridge to JavaScript from SwiftWasm apps anyway. The trade-offs are different though, but this will change as the ecosystem evolves.

**Comment by revolter** [comment]
So `TokamakStaticHTML` applies to the first point?

And, does this mean that I can use `DynamicHTML` with the second point? Meaning, still be able to deploy on GitHub Pages?

**Comment by MaxDesiatov** [comment]
> So `TokamakStaticHTML` applies to the first point?

Yes.

> And, does this mean that I can use `DynamicHTML` with the second point? Meaning, still be able to deploy on GitHub Pages?

Yes, you can deploy to GitHub Pages with `DynamicHTML` and the app will work in any relatively recent browser that supports WebAssembly. But the app binary will be relatively big, with size counted in megabytes, which may be too much for some apps running in a constrained environment where internet is slow. OTOH, the binary should stay in browser's cache after the first load.

**Comment by revolter** [comment]
Thank you very much for your help and for your work!!!

**Comment by MaxDesiatov** [comment]
No problem, let me know if you have any questions 🙂
